AK47:
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 5
    AMMO: 30
    TIME_BETWEEN_SHOTS: 1.5
    SCOPE: 13
BANANA: 
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 1
COWBOY_PISTOL:
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 7
    AMMO: 6
    SCOPE: 20
DUEL_PISTOL:
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 6
    AMMO: 1
    SCOPE: 5
GRENADE:
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 1
    EXPLOSION_RADIUS: 150
    DETONATION_TIME: 4
LASER_RIFLE: 
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 4
    AMMO: 10
    TIME_BETWEEN_SHOTS: 1.5
    SCOPE: 30
MAGNUM:
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 8
    AMMO: 6
    SCOPE: 20
PEW_PEW_LASER: 
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 3
    AMMO: 12
    TIME_BETWEEN_SHOTS: 1
    BURST_SHOTS: 3
    SCOPE: 38
SHOTGUN: 
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 9
    AMMO: 2
    SCOPE: 9
SNIPER: 
  - DIMENSION_X: 32
    DIMENSION_Y: 32
    TYPE: 10
    AMMO: 3
    TIME_BETWEEN_SHOTS: 1
    SCOPE: 64
